import { Provider } from "./provider";
import "../../tailwind.config";
import "@/style/global.css";
import Head from "next/head";

export const metadata = {
  title: "PiCK",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Head>
        <link rel="icon" href={metadata.icons.icon} />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
